export interface PokemonSet {
  name: string;
  code: string;
  series: string;
}

export const POKEMON_SETS: PokemonSet[] = [
  // Mega Evolution
  { name: "Chaos Rising", code: "CRI", series: "Mega Evolution" },
  { name: "Perfect Order", code: "POR", series: "Mega Evolution" },
  { name: "Ascended Heroes", code: "ASC", series: "Mega Evolution" },
  { name: "Phantasmal Flames", code: "PFL", series: "Mega Evolution" },
  { name: "Mega Evolution Energy", code: "MEE", series: "Mega Evolution" },
  { name: "Mega Evolution", code: "MEG", series: "Mega Evolution" },
  { name: "Mega Evolution Promos", code: "MEP", series: "Mega Evolution" },
  // Scarlet & Violet
  { name: "White Flare", code: "WHT", series: "Scarlet & Violet" },
  { name: "Scarlet & Violet Energy", code: "SVE", series: "Scarlet & Violet" },
  { name: "Black Bolt", code: "BLK", series: "Scarlet & Violet" },
  { name: "Destined Rivals", code: "DRI", series: "Scarlet & Violet" },
  { name: "Journey Together", code: "JTG", series: "Scarlet & Violet" },
  { name: "Prismatic Evolutions", code: "PRE", series: "Scarlet & Violet" },
  { name: "Surging Sparks", code: "SSP", series: "Scarlet & Violet" },
  { name: "Stellar Crown", code: "SCR", series: "Scarlet & Violet" },
  { name: "Shrouded Fable", code: "SFA", series: "Scarlet & Violet" },
  { name: "Twilight Masquerade", code: "TWM", series: "Scarlet & Violet" },
  { name: "Temporal Forces", code: "TEF", series: "Scarlet & Violet" },
  { name: "Paldean Fates", code: "PAF", series: "Scarlet & Violet" },
  { name: "Paradox Rift", code: "PAR", series: "Scarlet & Violet" },
  { name: "151", code: "MEW", series: "Scarlet & Violet" },
  { name: "McDonald's Match Battle 2023", code: "M23", series: "Scarlet & Violet" },
  { name: "Obsidian Flames", code: "OBF", series: "Scarlet & Violet" },
  { name: "Paldea Evolved", code: "PAL", series: "Scarlet & Violet" },
  { name: "Scarlet & Violet", code: "SVI", series: "Scarlet & Violet" },
  { name: "Scarlet & Violet Promos", code: "SVP", series: "Scarlet & Violet" },
  // Sword & Shield
  { name: "Crown Zenith", code: "CRZ", series: "Sword & Shield" },
  { name: "Silver Tempest", code: "SIT", series: "Sword & Shield" },
  { name: "Lost Origin", code: "LOR", series: "Sword & Shield" },
  { name: "McDonald's Collection 2022", code: "MCD22", series: "Sword & Shield" },
  { name: "Pokémon GO", code: "PGO", series: "Sword & Shield" },
  { name: "Astral Radiance", code: "ASR", series: "Sword & Shield" },
  { name: "Brilliant Stars", code: "BRS", series: "Sword & Shield" },
  { name: "Fusion Strike", code: "FST", series: "Sword & Shield" },
  { name: "Celebrations", code: "CEL", series: "Sword & Shield" },
  { name: "Evolving Skies", code: "EVS", series: "Sword & Shield" },
  { name: "Chilling Reign", code: "CRE", series: "Sword & Shield" },
  { name: "Battle Styles", code: "BST", series: "Sword & Shield" },
  { name: "Shining Fates", code: "SHF", series: "Sword & Shield" },
  { name: "Vivid Voltage", code: "VIV", series: "Sword & Shield" },
  { name: "Champion's Path", code: "CPA", series: "Sword & Shield" },
  { name: "Darkness Ablaze", code: "DAA", series: "Sword & Shield" },
  { name: "Rebel Clash", code: "RCL", series: "Sword & Shield" },
  { name: "Sword & Shield", code: "SSH", series: "Sword & Shield" },
  { name: "Pokémon Futsal Promos 2020", code: "FUT20", series: "Sword & Shield" },
  // Sun & Moon
  { name: "Cosmic Eclipse", code: "CEC", series: "Sun & Moon" },
  { name: "McDonald's Collection 2019", code: "MCD19", series: "Sun & Moon" },
  { name: "Hidden Fates", code: "HIF", series: "Sun & Moon" },
  { name: "Unified Minds", code: "UNM", series: "Sun & Moon" },
  { name: "Unbroken Bonds", code: "UNB", series: "Sun & Moon" },
  { name: "Detective Pikachu", code: "DET", series: "Sun & Moon" },
  { name: "Team Up", code: "TEU", series: "Sun & Moon" },
  { name: "Lost Thunder", code: "LOT", series: "Sun & Moon" },
  { name: "Dragon Majesty", code: "DRM", series: "Sun & Moon" },
  { name: "Celestial Storm", code: "CES", series: "Sun & Moon" },
  { name: "Forbidden Light", code: "FLI", series: "Sun & Moon" },
  { name: "Ultra Prism", code: "UPR", series: "Sun & Moon" },
  { name: "Crimson Invasion", code: "CIN", series: "Sun & Moon" },
  { name: "Shining Legends", code: "SLG", series: "Sun & Moon" },
  { name: "Burning Shadows", code: "BUS", series: "Sun & Moon" },
  { name: "Guardians Rising", code: "GRI", series: "Sun & Moon" },
  { name: "Sun & Moon", code: "SUM", series: "Sun & Moon" },
  { name: "Sun & Moon Promos", code: "SMP", series: "Sun & Moon" },
  // XY
  { name: "Evolutions", code: "EVO", series: "XY" },
  { name: "McDonald's Collection 2016", code: "MCD16", series: "XY" },
  { name: "Steam Siege", code: "STS", series: "XY" },
  { name: "Fates Collide", code: "FCO", series: "XY" },
  { name: "Generations", code: "GEN", series: "XY" },
  { name: "BREAKpoint", code: "BKP", series: "XY" },
  { name: "BREAKthrough", code: "BKT", series: "XY" },
  { name: "Ancient Origins", code: "AOR", series: "XY" },
  { name: "Roaring Skies", code: "ROS", series: "XY" },
  { name: "Double Crisis", code: "DCR", series: "XY" },
  { name: "Primal Clash", code: "PRC", series: "XY" },
  { name: "Phantom Forces", code: "PHF", series: "XY" },
  { name: "Furious Fists", code: "FFI", series: "XY" },
  { name: "Flashfire", code: "FLF", series: "XY" },
  { name: "XY", code: "XY", series: "XY" },
  { name: "Kalos Starter Set", code: "KSS", series: "XY" },
  { name: "XY Promos", code: "XYP", series: "XY" },
  // Black & White
  { name: "Legendary Treasures", code: "LTR", series: "Black & White" },
  { name: "Plasma Blast", code: "PLB", series: "Black & White" },
  { name: "Plasma Freeze", code: "PLF", series: "Black & White" },
  { name: "Plasma Storm", code: "PLS", series: "Black & White" },
  { name: "Boundaries Crossed", code: "BCR", series: "Black & White" },
  { name: "Dragon Vault", code: "DRV", series: "Black & White" },
  { name: "Dragons Exalted", code: "DRX", series: "Black & White" },
  { name: "McDonald's Collection 2012", code: "MCD12", series: "Black & White" },
  { name: "Dark Explorers", code: "DEX", series: "Black & White" },
  { name: "Next Destinies", code: "NXD", series: "Black & White" },
  { name: "Noble Victories", code: "NVI", series: "Black & White" },
  { name: "Emerging Powers", code: "EPO", series: "Black & White" },
  { name: "Black & White", code: "BLW", series: "Black & White" },
  { name: "Black & White Promos", code: "BWP", series: "Black & White" },
  // HeartGold & SoulSilver
  { name: "Call of Legends", code: "CL", series: "HeartGold & SoulSilver" },
  { name: "Triumphant", code: "TM", series: "HeartGold & SoulSilver" },
  { name: "Undaunted", code: "UD", series: "HeartGold & SoulSilver" },
  { name: "Unleashed", code: "UL", series: "HeartGold & SoulSilver" },
  { name: "HeartGold & SoulSilver", code: "HS", series: "HeartGold & SoulSilver" },
  // Platinum
  { name: "Arceus", code: "AR", series: "Platinum" },
  { name: "Supreme Victors", code: "SV", series: "Platinum" },
  { name: "Rising Rivals", code: "RR", series: "Platinum" },
  { name: "Platinum", code: "PL", series: "Platinum" },
  // Diamond & Pearl
  { name: "Stormfront", code: "SF", series: "Diamond & Pearl" },
  { name: "Legends Awakened", code: "LA", series: "Diamond & Pearl" },
  { name: "Majestic Dawn", code: "MD", series: "Diamond & Pearl" },
  { name: "Great Encounters", code: "GE", series: "Diamond & Pearl" },
  { name: "Secret Wonders", code: "SW", series: "Diamond & Pearl" },
  { name: "Mysterious Treasures", code: "MT", series: "Diamond & Pearl" },
  { name: "Diamond & Pearl", code: "DP", series: "Diamond & Pearl" },
  // EX
  { name: "Power Keepers", code: "PK", series: "EX" },
  { name: "Dragon Frontiers", code: "DF", series: "EX" },
  { name: "Crystal Guardians", code: "CG", series: "EX" },
  { name: "Holon Phantoms", code: "HP", series: "EX" },
  { name: "Legend Maker", code: "LM", series: "EX" },
  { name: "Delta Species", code: "DS", series: "EX" },
  { name: "Unseen Forces", code: "UF", series: "EX" },
  { name: "Emerald", code: "EM", series: "EX" },
  { name: "Deoxys", code: "DX", series: "EX" },
  { name: "Team Rocket Returns", code: "TR", series: "EX" },
  { name: "FireRed & LeafGreen", code: "RG", series: "EX" },
  { name: "Hidden Legends", code: "HL", series: "EX" },
  { name: "Team Magma vs Team Aqua", code: "MA", series: "EX" },
  { name: "Dragon", code: "DR", series: "EX" },
  { name: "Sandstorm", code: "SS", series: "EX" },
  { name: "Ruby & Sapphire", code: "RS", series: "EX" },
  // E-Card
  { name: "Skyridge", code: "SK", series: "E-Card" },
  { name: "Aquapolis", code: "AQ", series: "E-Card" },
  { name: "Expedition", code: "EX", series: "E-Card" },
  // Neo
  { name: "Neo Destiny", code: "N4", series: "Neo" },
  { name: "Neo Revelation", code: "N3", series: "Neo" },
  { name: "Neo Discovery", code: "N2", series: "Neo" },
  { name: "Neo Genesis", code: "N1", series: "Neo" },
  // Gym
  { name: "Gym Challenge", code: "G2", series: "Gym" },
  { name: "Gym Heroes", code: "G1", series: "Gym" },
  // Classic
  { name: "Team Rocket", code: "RO", series: "Classic" },
  { name: "Base Set 2", code: "B2", series: "Classic" },
  { name: "Fossil", code: "FO", series: "Classic" },
  { name: "Jungle", code: "JU", series: "Classic" },
  { name: "Base Set", code: "BS", series: "Classic" },
  // POP
  { name: "POP Series 9", code: "P9", series: "POP" },
  { name: "POP Series 8", code: "P8", series: "POP" },
  { name: "POP Series 7", code: "P7", series: "POP" },
  { name: "POP Series 6", code: "P6", series: "POP" },
  { name: "POP Series 5", code: "P5", series: "POP" },
  { name: "POP Series 4", code: "P4", series: "POP" },
  { name: "POP Series 3", code: "P3", series: "POP" },
  { name: "POP Series 2", code: "P2", series: "POP" },
  { name: "POP Series 1", code: "P1", series: "POP" },
];
